# frozen_string_literal: true

require "test_helper"
require "rake"

class UserFavoritesRakeTaskTest < ActiveSupport::TestCase
  RETIRED = Services::BooksMigration::ListMigrator::SUPERSEDED_LIST_NAMES

  setup do
    # Deliberately not `Rails.application.load_tasks`: that walks every
    # railtie's rake_tasks hook, and cssbundling-rails registers its
    # `lib/tasks/cssbundling/build.rake` through both its own hook and Rails'
    # generic per-engine `lib/tasks/**/*.rake` glob, so calling it a second
    # time in an already-booted process re-`load`s that file and Ruby warns
    # "already initialized constant Cssbundling::Tasks::LOCK_FILES" -- a new,
    # unrelated warning line in `bin/rails test`. Loading only the one file
    # this test needs avoids that entirely.
    unless Rake::Task.task_defined?("user_favorites_lists:rebuild")
      Rake::Task.define_task(:environment) {} unless Rake::Task.task_defined?(:environment)
      load Rails.root.join("lib/tasks/lists/user_favorites.rake").to_s
    end
    Rake::Task["user_favorites_lists:rebuild"].reenable
  end

  # capture_io: the task narrates every step on stdout, and `bin/rails test` is
  # expected to run clean -- an unswallowed puts here is a dozen new lines of
  # noise in the suite output.
  def rebuild
    out, _err = capture_io { Rake::Task["user_favorites_lists:rebuild"].invoke }
    Rake::Task["user_favorites_lists:rebuild"].reenable
    out
  end

  def generated_books_list
    ::Books::List.find_by(auto_generated_kind: :user_favorites)
  end

  test "rebuild deletes the retired legacy lists whose auto_generated_kind is nil" do
    doomed = RETIRED.map do |name|
      list = ::Books::List.create!(type: "Books::List", name: name, status: :active)
      list.list_items.create!(listable: books_books(:crime_and_punishment), position: 1)
      list
    end

    rebuild

    doomed.each do |list|
      assert_not ::Books::List.exists?(list.id), "left #{list.name.inspect} behind"
    end
  end

  test "rebuild never deletes the generated list, even when it is empty" do
    # Deliberately EMPTY, and deliberately carrying one of the retired names --
    # ::Books::UserList.generated_list_name IS the third of them. A generated
    # list holding items is protected twice over: by the doomed query's
    # auto_generated_kind filter (the thing under test) and, incidentally, by
    # the ListItem destroy guard raising from inside the cascade. With an item
    # present, deleting the filter still leaves the list standing and this test
    # still passes -- against the exact regression it exists to catch. Empty,
    # the filter is the only thing standing between the task and the list.
    #
    # Verified non-vacuous: dropping `auto_generated_kind: nil` from the doomed
    # query turns this test red. Note what it goes red WITH --
    # List::AutoGeneratedListError from List#prevent_destroy_when_auto_generated,
    # not a missing row. The model guard means the generated list cannot in fact
    # be destroyed; the filter's real job is to stop `rebuild` from raising on
    # every run in a database that has one.
    keep = ::Books::List.create!(
      type: "Books::List",
      name: ::Books::UserList.generated_list_name,
      status: :active,
      auto_generated_kind: :user_favorites
    )
    assert_empty keep.list_items

    rebuild

    assert ::Books::List.exists?(keep.id)
    assert_equal keep.id, generated_books_list.id
  end

  # rebuild is an explicit operator action -- "make this correct now" -- so unlike
  # the nightly job it DOES override a deactivation. This is the production repair
  # path: the parent PR created the books list unapproved, unranked and unpenalised.
  test "rebuild activates and wires an unapproved generated list" do
    ::Global::Penalty.create!(name: Services::Lists::GenerateUserFavorites::STANDARD_PENALTY_NAME)
    keep = ::Books::List.create!(
      type: "Books::List",
      name: ::Books::UserList.generated_list_name,
      status: :unapproved,
      auto_generated_kind: :user_favorites
    )

    out = rebuild

    assert_equal "active", keep.reload.status
    assert_equal ::Books::RankingConfiguration.default_primary, keep.ranked_lists.sole.ranking_configuration
    assert_equal [Services::Lists::GenerateUserFavorites::STANDARD_PENALTY_NAME], keep.penalties.map(&:name)
    assert_match(/unapproved/, out)
  end

  test "rebuild says nothing about status when the list is already active" do
    keep = ::Books::List.create!(
      type: "Books::List",
      name: ::Books::UserList.generated_list_name,
      status: :active,
      auto_generated_kind: :user_favorites
    )

    out = rebuild

    assert_equal "active", keep.reload.status
    refute_match(/Activated/, out)
  end

  test "rebuild creates the generated list wired up when there is none" do
    ::Global::Penalty.create!(name: Services::Lists::GenerateUserFavorites::STANDARD_PENALTY_NAME)
    assert_nil generated_books_list

    rebuild

    list = generated_books_list
    assert_not_nil list
    assert_equal "active", list.status
    assert_equal ::Books::RankingConfiguration.default_primary, list.ranked_lists.sole.ranking_configuration
    assert_equal [Services::Lists::GenerateUserFavorites::STANDARD_PENALTY_NAME], list.penalties.map(&:name)
  end

  test "rebuild backfills manually_ordered before generating" do
    Services::UserLists::BackfillManuallyOrdered.expects(:call).once.returns(0)

    rebuild
  end

  test "rebuild is idempotent" do
    doomed = ::Books::List.create!(type: "Books::List", name: RETIRED.first, status: :active)

    rebuild
    first = generated_books_list
    assert_not_nil first
    counts = [::Books::List.count, ::ListItem.count, ::RankedList.count, ::ListPenalty.count]

    rebuild

    assert_not ::Books::List.exists?(doomed.id)
    assert_equal first.id, generated_books_list.id
    assert_equal counts, [::Books::List.count, ::ListItem.count, ::RankedList.count, ::ListPenalty.count]
  end
end
