services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    command: >
      postgres -c 'log_statement=all'
               -c 'log_min_messages=debug1'
               -c 'log_min_error_statement=error'
    networks:
      - the-greatest

volumes:
  postgresql-data:
    name: tg_postgresql_data 

networks:
  the-greatest:
    driver: bridge