services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    command: >
      postgres -c 'log_statement=all'
               -c 'log_min_messages=debug1'
               -c 'log_min_error_statement=error'
    networks:
      - the-greatest
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-dev
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${DOCKER_OPENSEARCH_PASSWORD} # required even if security is disabled
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - the-greatest
    ports:
      - "9200:9200"
      - "9600:9600"
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - the-greatest
    command: redis-server --appendonly yes

volumes:
  postgresql-data:
    name: tg_postgresql_data 
  opensearch-data:
    name: tg_opensearch_data
  redis-data:
    name: tg_redis_data

networks:
  the-greatest:
    driver: bridge