# == Schema Information
#
# Table name: lists
#
#  id                    :bigint           not null, primary key
#  activated_at          :datetime
#  auto_generated_kind   :integer
#  category_specific     :boolean
#  creator_specific      :boolean
#  description           :text
#  estimated_quality     :integer          default(0), not null
#  high_quality_source   :boolean
#  items_json            :jsonb
#  location_specific     :boolean
#  name                  :string           not null
#  num_years_covered     :integer
#  number_of_voters      :integer
#  raw_content           :text
#  simplified_content    :text
#  source                :string
#  source_country_origin :string
#  status                :integer          default(0), not null
#  submitted_at          :datetime
#  submitter_email       :string
#  submitter_ip          :string
#  type                  :string           not null
#  url                   :string
#  voter_count_estimated :boolean
#  voter_count_unknown   :boolean
#  voter_names_unknown   :boolean
#  wizard_state          :jsonb
#  year_published        :integer
#  yearly_award          :boolean
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  musicbrainz_series_id :string
#  submitted_by_id       :bigint
#
# Indexes
#
#  index_lists_on_activated_at                  (activated_at)
#  index_lists_on_submitted_at                  (submitted_at)
#  index_lists_on_submitted_by_id               (submitted_by_id)
#  index_lists_on_type_and_auto_generated_kind  (type,auto_generated_kind) UNIQUE WHERE (auto_generated_kind IS NOT NULL)
#
# Foreign Keys
#
#  fk_rails_...  (submitted_by_id => users.id)
#
class List < ApplicationRecord
  # Raised to block the deletion of a list the generator owns.
  #
  # Deliberately NOT a subclass of ActiveRecord::RecordNotDestroyed, for the
  # same reason as ListItem::AutoGeneratedListItemError: ActiveRecord::Callbacks#destroy
  # rescues that one class specifically (activerecord-8.1.3.1/lib/active_record/callbacks.rb:424),
  # turning it into a plain `false` return, which #destroy and Relation#destroy_all
  # then swallow without a word. A plain StandardError has no such special case
  # and propagates through every destroy path alike.
  class AutoGeneratedListError < StandardError; end

  # Associations
  has_many :list_items, dependent: :destroy
  belongs_to :submitted_by, class_name: "User", optional: true
  has_many :list_penalties, dependent: :destroy, inverse_of: :list
  has_many :penalties, through: :list_penalties, inverse_of: :lists
  has_many :ai_chats, as: :parent, dependent: :destroy
  # ranked_lists.list_id carries no foreign key, so without this a destroyed list
  # silently leaves an orphan RankedList row behind and the admin ranked-lists
  # view then raises on rl.list.name.
  has_many :ranked_lists, dependent: :destroy

  # Enums
  enum :status, {unapproved: 0, approved: 1, rejected: 2, active: 3}
  # Set on lists whose items are written by a generator rather than curated by
  # hand. Identifies the generated list durably across renames -- the legacy
  # implementation looked its lists up by name, which broke on any edit.
  # Prefixed so the predicate reads generated_user_favorites? rather than
  # colliding with a bare user_favorites? on List.
  enum :auto_generated_kind, {user_favorites: 0}, prefix: :generated

  # Set by Services::Lists::Submission only. The simplifier is a Nokogiri parse
  # and auto_simplify_content runs it inline on every new record carrying
  # raw_content -- on an anonymous public endpoint that is a CPU lever, and
  # production raw_content reaches 1.5 MB. Deferring is safe because
  # Services::Lists::ImportService recomputes simplified_content unconditionally
  # before it parses, so nothing downstream needs it at insert time.
  attr_accessor :skip_content_simplification

  # Callbacks
  before_validation :parse_items_json_if_string
  before_save :auto_simplify_content, if: :should_simplify_content?
  before_save :stamp_activated_at, if: -> { status_changed? && active? }
  before_destroy :prevent_destroy_when_auto_generated

  # Validations
  validates :name, presence: true
  validates :type, presence: true
  validates :status, presence: true
  validates :url, format: {with: %r{\Ahttps?://}i, message: "must be an http or https url"}, allow_blank: true
  validates :num_years_covered, numericality: {greater_than: 0, only_integer: true}, allow_nil: true
  validate :items_json_format

  # Scopes
  scope :approved, -> { where(status: :approved) }
  scope :high_quality, -> { where(high_quality_source: true) }
  scope :by_year, ->(year) { where(year_published: year) }
  scope :yearly_awards, -> { where(yearly_award: true) }
  scope :search_by_name, ->(query) {
    return all if query.blank?
    sanitized = "%" + sanitize_sql_like(query.to_s.strip) + "%"
    where("name ILIKE ? OR source ILIKE ?", sanitized, sanitized)
  }
  scope :search_text, ->(query) {
    return all if query.blank?
    sanitized = "%" + sanitize_sql_like(query.to_s.strip) + "%"
    where("name ILIKE :q OR source ILIKE :q OR url ILIKE :q", q: sanitized)
  }

  # Public Methods
  def has_penalties?
    penalties.any?
  end

  def auto_generated?
    auto_generated_kind.present?
  end

  def global_penalties
    penalties.global
  end

  def user_penalties
    penalties.user_specific
  end

  def parse_with_ai!
    Services::Lists::ImportService.call(self)
  end

  # Returns the wizard state manager for this list.
  # The manager provides all wizard state operations.
  #
  # @return [Services::Lists::Wizard::StateManager] the state manager instance
  def wizard_manager
    @wizard_manager ||= Services::Lists::Wizard::StateManager.for(self)
  end

  # Only books carry country-of-origin data, so every other media type answers
  # nil and the weight calculator skips the western-canon penalty.
  def percentage_western
    nil
  end

  def self.median_list_count(type: nil)
    # Get lists of the specified type, or all lists if no type specified
    scope = type ? where(type: type) : all

    # Get list item counts for lists that have items
    counts = scope.joins(:list_items)
      .group("lists.id")
      .count("list_items.id")
      .values
      .sort

    return 0 if counts.empty?

    # Calculate median
    len = counts.length
    if len.odd?
      counts[len / 2]
    else
      (counts[len / 2 - 1] + counts[len / 2]) / 2.0
    end
  end

  private

  def should_simplify_content?
    return false if skip_content_simplification

    raw_content.present? && (new_record? || raw_content_changed?)
  end

  def auto_simplify_content
    self.simplified_content = Services::Html::SimplifierService.call(raw_content)
  end

  def stamp_activated_at
    self.activated_at = Time.current
  end

  # The generated list owns a public URL, a RankedList row with a hand-tuned
  # weight, and its penalties. Deleting it takes all of that with it, and the
  # nightly generator would then silently recreate a fresh, unweighted, unapproved
  # one under a new id. The item-level guard cannot stand in for this: it exempts
  # parent cascades (it has to -- see ListItem#prevent_destroy_when_auto_generated),
  # and an empty generated list has no items to object at all.
  #
  # Recovering from a mistaken flag is a console job, deliberately: auto_generated_kind
  # is not in the admin's permitted params.
  def prevent_destroy_when_auto_generated
    return unless auto_generated?

    raise AutoGeneratedListError, "This list is managed by the generator and cannot be deleted"
  end

  def parse_items_json_if_string
    return unless items_json.is_a?(String) && items_json.present?

    begin
      self.items_json = JSON.parse(items_json)
    rescue JSON::ParserError
      # Let the validation catch this
    end
  end

  def items_json_format
    return if items_json.blank?
    return if items_json.is_a?(Hash) || items_json.is_a?(Array)

    # If it's a string, try to parse it
    if items_json.is_a?(String)
      JSON.parse(items_json)
    end
  rescue JSON::ParserError => e
    errors.add(:items_json, "must be valid JSON: #{e.message}")
  end
end
