# == Schema Information
#
# Table name: list_items
#
#  id            :bigint           not null, primary key
#  listable_type :string
#  metadata      :jsonb
#  position      :integer
#  verified      :boolean          default(FALSE), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  list_id       :bigint           not null
#  listable_id   :bigint
#
# Indexes
#
#  index_list_items_on_list_and_listable_unique  (list_id,listable_type,listable_id) UNIQUE
#  index_list_items_on_list_id                   (list_id)
#  index_list_items_on_list_id_and_position      (list_id,position)
#  index_list_items_on_listable                  (listable_type,listable_id)
#
# Foreign Keys
#
#  fk_rails_...  (list_id => lists.id)
#
class ListItem < ApplicationRecord
  # Raised to block a hand edit against an auto-generated list's items.
  #
  # Deliberately NOT a subclass of ActiveRecord::RecordNotDestroyed.
  # ActiveRecord::Callbacks#destroy specifically rescues that one class,
  # converting it to a plain `false` return so that #destroy! can re-raise it
  # with a friendlier message -- which means raising it from a before_destroy
  # callback is silently swallowed by plain #destroy, and therefore also by
  # ActiveRecord::Relation#destroy_all (list.list_items.where(...).destroy_all),
  # which calls #destroy per record and never checks the result. Measured
  # empirically against this branch: with RecordNotDestroyed, item.destroy
  # returns false with no exception, and a narrowed destroy_all returns as if
  # it succeeded while the row survives. A plain StandardError has no such
  # special case anywhere in Rails and propagates through every destroy path
  # alike: #destroy, #destroy!, association destroy_all, and Relation#destroy_all.
  class AutoGeneratedListItemError < StandardError; end

  belongs_to :list, touch: true
  belongs_to :listable, polymorphic: true, optional: true
  alias_method :item, :listable

  # Callbacks
  before_validation :parse_metadata_if_string
  before_destroy :prevent_destroy_when_auto_generated

  # Validations
  validates :list, presence: true
  validates :position, numericality: {greater_than: 0}, allow_blank: true
  validates :listable_id, uniqueness: {scope: [:list_id, :listable_type], message: "is already in this list"}, allow_nil: true
  validate :listable_type_compatible_with_list_type
  validate :metadata_format
  validate :list_must_not_be_auto_generated

  private

  def parse_metadata_if_string
    return unless metadata.is_a?(String) && metadata.present?

    begin
      self.metadata = JSON.parse(metadata)
    rescue JSON::ParserError
      # Let the validation catch this
    end
  end

  def metadata_format
    return if metadata.blank?
    return if metadata.is_a?(Hash) || metadata.is_a?(Array)

    if metadata.is_a?(String)
      JSON.parse(metadata)
    end
  rescue JSON::ParserError => e
    errors.add(:metadata, "must be valid JSON: #{e.message}")
  end

  def listable_type_compatible_with_list_type
    return if listable_type.blank? || list.blank?

    expected_type = case list.class.name
    when "Music::Albums::List"
      "Music::Album"
    when "Music::Songs::List"
      "Music::Song"
    when "Books::List"
      "Books::Book"
    when "Movies::List"
      "Movies::Movie"
    when "Games::List"
      "Games::Game"
    end

    if expected_type && listable_type != expected_type
      errors.add(:listable_type, "#{listable_type} is not compatible with list type #{list.class.name}")
    end
  end

  # The generator owns an auto-generated list's items and rewrites them on every
  # run, so anything edited by hand is destroyed on the next pass. Refuse the
  # edit rather than lose it silently.
  #
  # Services::Lists::GenerateUserFavorites writes through delete_all / insert_all,
  # which skip callbacks and validations by design -- so this guard needs no
  # escape hatch for the job itself.
  def list_must_not_be_auto_generated
    return if list.nil? || !list.auto_generated?

    errors.add(:base, "Items on an auto-generated list are managed by the generator and cannot be edited")
  end

  # Raising (rather than throw :abort) closes the destroy_all hole described
  # on AutoGeneratedListItemError above at every call site at once, instead of
  # patching each one.
  def prevent_destroy_when_auto_generated
    # ListItem is the dependent of FIVE owners, not one: List, plus Books::Book,
    # Music::Album, Music::Song and Games::Game as :listable. Raising propagates
    # out of every dependent-destroy cascade alike, so without this exemption any
    # book/album/song/game that happens to appear on its domain's generated list
    # becomes permanently undeletable. destroyed_by_association is set only when a
    # parent is cascading -- measured on this branch: list cascade and book cascade
    # both report :list_items, while a direct destroy and Relation#destroy_all
    # report nil. A cascade is not a hand edit.
    #
    # The generated List itself is protected one level up, by
    # List#prevent_destroy_when_auto_generated -- not here.
    return if destroyed_by_association.present?
    return if list.nil? || !list.auto_generated?

    raise AutoGeneratedListItemError, "Items on an auto-generated list are managed by the generator and cannot be edited"
  end

  # Scopes
  scope :ordered, -> { order(:position) }
  scope :by_list, ->(list) { where(list: list) }
  scope :by_listable_type, ->(type) { where(listable_type: type) }
  scope :with_listable, -> { where.not(listable_id: nil) }
  scope :without_listable, -> { where(listable_id: nil) }
  scope :verified, -> { where(verified: true) }
  scope :unverified, -> { where(verified: false) }
end
