module Services
  module BooksMigration
    # Legacy `authors` row -> new Books::Author attributes. `kind` is intentionally
    # omitted so the model default (:person) applies; `slug` is generated by
    # FriendlyId on save. `alternate_names` is NOT NULL default [] in the new
    # schema, so nil coerces to [].
    class AuthorTransformer
      def self.call(attrs)
        {
          name: attrs["name"],
          sort_name: attrs["family_name"].presence || attrs["name"],
          birth_year: attrs["birth_year"],
          death_year: attrs["death_year"],
          description: attrs["description"],
          alternate_names: Array(attrs["alternative_names"])
        }
      end
    end
  end
end
