module Services
  module BooksMigration
    # Legacy `books` row -> new Books::Book attributes. PURE: the language FK is
    # remapped by BookMigrator (needs a DB lookup), not here. `book_kind` is
    # omitted so the model default (:standalone) applies; `slug` is generated by
    # FriendlyId on save. `alternate_titles` is NOT NULL default [] in the new
    # schema, so it always resolves to an array (legacy `alternate_titles` array
    # plus the single `alternate_title_1`, blanks dropped, de-duplicated).
    class BookTransformer
      def self.call(attrs)
        {
          title: attrs["title"],
          subtitle: attrs["sub_title"],
          description: attrs["description"],
          first_published_year: attrs["first_year_published"],
          sort_title: attrs["sort_title"],
          alternate_titles: alternate_titles(attrs)
        }
      end

      def self.alternate_titles(attrs)
        (Array(attrs["alternate_titles"]) + [attrs["alternate_title_1"]]).compact_blank.uniq
      end
      private_class_method :alternate_titles
    end
  end
end
