module Services
  module BooksMigration
    # The reviewed per-list num_years_covered values: a plain `id: years` YAML
    # mapping written as text so the reviewer's comments survive. `load` returns
    # the values only; `append` adds entries for ids the file does not already
    # carry and never rewrites an existing line, so hand edits are safe across
    # regenerations. Delete the file to start over.
    class NumYearsCoveredFile
      PATH = Rails.root.join("config/books_migration/num_years_covered.yml")

      HEADER = <<~YAML
        # Books lists: number of publication years the list's scope allowed.
        # Generated by `bin/rails data_migration:num_years_covered:derive` from the LEGACY
        # database. Edit values freely; existing entries are never rewritten. Delete the
        # file to regenerate from scratch. Read by NumYearsCoveredMigrator (values only).
        #
        # id: years   # list name  (legacy bucket -> how the number was derived)
      YAML

      def self.load(path = PATH)
        return {} unless File.exist?(path)

        data = YAML.safe_load_file(path) || {}
        data.each do |id, years|
          next if id.is_a?(Integer) && years.is_a?(Integer) && years.positive?

          raise ArgumentError, "#{path}: entry #{id.inspect}: #{years.inspect} is not a positive integer"
        end
        data
      end

      # entries: objects responding to #id and #to_line (NumYearsCoveredDeriver::Entry).
      def self.append(entries, path = PATH)
        known = load(path).keys.to_set
        fresh = entries.reject { |entry| known.include?(entry.id) }
        return {kept: known.size, added: 0} if fresh.empty?

        existing = File.exist?(path) ? File.read(path) : HEADER
        existing += "\n" unless existing.end_with?("\n")
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, existing + fresh.map(&:to_line).join("\n") + "\n")
        {kept: known.size, added: fresh.size}
      end
    end
  end
end
