// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import AuthenticationController from "./authentication_controller"
import AdminSearchController from "./admin/search_controller"

application.register("authentication", AuthenticationController)
application.register("admin--search", AdminSearchController)
