// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__SearchController from "./admin/search_controller"
application.register("admin--search", Admin__SearchController)

import AuthenticationController from "./authentication_controller"
application.register("authentication", AuthenticationController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import ClipboardCopyController from "./clipboard_copy_controller"
application.register("clipboard-copy", ClipboardCopyController)

import MetadataEditorController from "./metadata_editor_controller"
application.register("metadata-editor", MetadataEditorController)

import ModalFormController from "./modal_form_controller"
application.register("modal-form", ModalFormController)

import ReviewFilterController from "./review_filter_controller"
application.register("review-filter", ReviewFilterController)

import SharedModalController from "./shared_modal_controller"
application.register("shared-modal", SharedModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UserListModalController from "./user_list_modal_controller"
application.register("user-list-modal", UserListModalController)

import UserListStateController from "./user_list_state_controller"
application.register("user-list-state", UserListStateController)

import UserListWidgetController from "./user_list_widget_controller"
application.register("user-list-widget", UserListWidgetController)

import WizardStepController from "./wizard_step_controller"
application.register("wizard-step", WizardStepController)

import YearRangeModalController from "./year_range_modal_controller"
application.register("year-range-modal", YearRangeModalController)
