// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__MarkdownPreviewController from "./admin/markdown_preview_controller"
application.register("admin--markdown-preview", Admin__MarkdownPreviewController)

import Admin__SearchController from "./admin/search_controller"
application.register("admin--search", Admin__SearchController)

import AutoDismissController from "./auto_dismiss_controller"
application.register("auto-dismiss", AutoDismissController)

import AuthenticationController from "./authentication_controller"
application.register("authentication", AuthenticationController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import Books__FilterController from "./books/filter_controller"
application.register("books--filter", Books__FilterController)

import ClipboardCopyController from "./clipboard_copy_controller"
application.register("clipboard-copy", ClipboardCopyController)

import MembershipStateController from "./membership_state_controller"
application.register("membership-state", MembershipStateController)

import ReviewFilterController from "./review_filter_controller"
application.register("review-filter", ReviewFilterController)

import Reviews__ModalController from "./reviews/modal_controller"
application.register("reviews--modal", Reviews__ModalController)

import Reviews__MyReviewsController from "./reviews/my_reviews_controller"
application.register("reviews--my-reviews", Reviews__MyReviewsController)

import Reviews__SpoilerController from "./reviews/spoiler_controller"
application.register("reviews--spoiler", Reviews__SpoilerController)

import Reviews__WidgetController from "./reviews/widget_controller"
application.register("reviews--widget", Reviews__WidgetController)

import SavedSearchPickerController from "./saved_search_picker_controller"
application.register("saved-search-picker", SavedSearchPickerController)

import SharedModalController from "./shared_modal_controller"
application.register("shared-modal", SharedModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UserListAddItemController from "./user_list_add_item_controller"
application.register("user-list-add-item", UserListAddItemController)

import UserListModalController from "./user_list_modal_controller"
application.register("user-list-modal", UserListModalController)

import UserListStateController from "./user_list_state_controller"
application.register("user-list-state", UserListStateController)

import UserListWidgetController from "./user_list_widget_controller"
application.register("user-list-widget", UserListWidgetController)

import WizardStepController from "./wizard_step_controller"
application.register("wizard-step", WizardStepController)

import YearRangeModalController from "./year_range_modal_controller"
application.register("year-range-modal", YearRangeModalController)
