class AddAutoGeneratedKindToLists < ActiveRecord::Migration[8.1]
  def change
    add_column :lists, :auto_generated_kind, :integer

    # One generated list of each kind per domain. Partial so the column stays
    # NULL for the ~600 hand-curated lists without them colliding with each other.
    add_index :lists, [:type, :auto_generated_kind],
      unique: true,
      where: "auto_generated_kind IS NOT NULL",
      name: "index_lists_on_type_and_auto_generated_kind"
  end
end
