class AddAutoGeneratedYearToLists < ActiveRecord::Migration[8.1]
  def change
    add_column :lists, :auto_generated_year, :integer

    remove_index :lists, name: "index_lists_on_type_and_auto_generated_kind"

    # NULLS NOT DISTINCT keeps user_favorites rows -- whose year is NULL --
    # collapsed to one per domain exactly as the old index did, while allowing
    # one year_top and one year_honorable_mention per year per domain.
    # PostgreSQL is 17.4 and Rails 8.1 round-trips this through the schema
    # dumper, so one index replaces what would otherwise be two partial ones.
    add_index :lists, [:type, :auto_generated_kind, :auto_generated_year],
      unique: true,
      nulls_not_distinct: true,
      where: "auto_generated_kind IS NOT NULL",
      name: "index_lists_on_type_and_auto_generated_kind_and_year"
  end
end
