class AddAutoGeneratedYearToLists < ActiveRecord::Migration[8.1]
  def change
    add_column :lists, :auto_generated_year, :integer

    # Full original definition supplied (not just name:) so CommandRecorder
    # can invert this remove_index on rollback -- invert_remove_index requires
    # :column (Rails 8.1 activerecord/lib/active_record/migration/command_recorder.rb),
    # and without it `db:rollback` on this migration raises IrreversibleMigration.
    remove_index :lists, name: "index_lists_on_type_and_auto_generated_kind",
      column: [:type, :auto_generated_kind],
      unique: true,
      where: "auto_generated_kind IS NOT NULL"

    # NULLS NOT DISTINCT keeps user_favorites rows -- whose year is NULL --
    # collapsed to one per domain exactly as the old index did, while allowing
    # one year_top and one year_honorable_mention per year per domain.
    # PostgreSQL is 17.4 and Rails 8.1 round-trips this through the schema
    # dumper, so one index replaces what would otherwise be two partial ones.
    add_index :lists, [:type, :auto_generated_kind, :auto_generated_year],
      unique: true,
      nulls_not_distinct: true,
      where: "auto_generated_kind IS NOT NULL",
      name: "index_lists_on_type_and_auto_generated_kind_and_year"
  end
end
