name: Deploy to Production

on:
  workflow_dispatch:
  repository_dispatch:
    types: [image-built-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
        with:
          host: ${{ secrets.SERVER_WEB_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: AGE_PRIVATE_KEY
          script: |
            set -e
            cd /home/deploy/apps/the-greatest

            # Clean up Docker resources
            docker system prune -f

            # Pull latest code (includes encrypted secrets)
            git pull

            # Write age key and decrypt secrets
            mkdir -p ~/.config/sops/age
            printf "%s" "$AGE_PRIVATE_KEY" > ~/.config/sops/age/keys.txt
            chmod 600 ~/.config/sops/age/keys.txt
            export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt

            # Decrypt secrets to .env
            sops -d secrets/.env.production > .env.new
            mv .env.new .env
            chmod 600 .env

            # Clean up age key
            rm -f ~/.config/sops/age/keys.txt

            # Pull web/worker images and rebuild nginx
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml build --no-cache nginx
            docker compose -f docker-compose.prod.yml up -d
